vars <- c("character","character",rep("numeric",7))
data <- read.table("household_power_consumption.txt", h= 1,sep =";", colClasses = vars,na.strings="?")
dataToRead <- subset(data, (data$Date == "1/2/2007")|(data$Date == "2/2/2007"))
abc <- as.POSIXct(paste(dataToRead$Date,dataToRead$Time), format = "%d/%m/%Y %H:%M:%S")
plot(abc, dataToRead$Global_active_power, type= "l", ylab = "Global Active Power (killowatts)", xlab = "")
dev.copy(png,file = "Plot2.png")
dev.off()